---
title: "Introduction to appifyr"
author: "Reto Wyss"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Motivation

There currently are two packages that allow useRs to build web apps with R: Shiny and OpenCPU. They both have some drawbacks. While Shiny makes it simple to create inputs and outputs, it requires the useR to write Shiny specific code. On the other hand, OpenCPU does not provide any boilerplate functions to create input and output elements. So, useRs need to write JavaScript and html to create a functional app. However, OpenCPU is a more indepentant platform and can be scaled without using the proprietory Shiny Server Pro. 

This is where appifyr comes in. It tries to make the OpenCPU engine more accessible for useRs with little to none knowledge of JavaScript and html.  

Appifyr makes it easy to build apps. Appifyr takes package functions or functions in your rmarkdown document (experimental) and turns them into an app. It does this by using JavaScript and html templates. The function arguments will be linked to the html-form input. Appifyr creates html-id-tags to indentify the form-input. When you click submit the values are read from the form and a request is sent to the OpenCPU server. The OpenCPU server then executes the R-function. The R-function's output is then handled by the Javascript callback and displayed to the user.

This video show a timelapsed workflow.

<iframe width="100%" height="480" src="https://www.youtube.com/embed/CAlBD6_T374" frameborder="0" gesture="media" allow="encrypted-media" allowfullscreen></iframe>

# Installation

First, you need to install `devtools` from CRAN.

```
install.packages("devtools")
```

Second, install `appifyr`. It has a fair amount of package dependancies in its own right, these will be installed automatically. 

```
devtools::install_github("retowyss/appifyr")
```

Third, install OpenCPU. It too has a bunch of dependancies. If you are using Ubuntu/Debian you might have to install some additional system libraries.

```
install.packages("opencpu")
```

Fourth, you need roxygen2 to create package documentation.

```
install.packages("roxygen2")
```

# Working with appifyr

If you want to create an app with appifyr you will be creating an R-package. Appifyr just writes Javascript and html for you. The app runs on the OpenCPU server. OpenCPU can only make package functions available. There are excellent resources out there to learn about R-package, my favorite one is Hadley Wickhams R-Package book. It's a good idea to familiaize yourself with the basics of writing R-package but it's not a requirement to play around with appifyr.

You start out by creating a new R-package (project) in RStudio. From here on I will assume you've named your package "MyAppifyrApp". To get set up you run:

```
appifyr::new_app()
```

This will create and delete some files in your R-package directory. You can navigate to `app/website/` and open up the `index.Rmd` file. There is a working appifyr app embeded in its R-chunk. The template in `app/website/` is a R-markdown website - a set of Rmarkdown files that will be rendered into a fully functional website. The `.yml` file controls how this is done. You can learn more about Rmarkdown websites [here](http://rmarkdown.rstudio.com/rmarkdown_websites.html).

The template is functional right out of the box. You can try it by running:

```
appifyr::build_app()
opencpu::ocpu_start_app("MyAppifyrApp")
```

When devolping apps with OpenCPU you might have to hard refresh (Shift+F5) the page in your browser to clear the cache after making changes to the website.

In the `index.Rmd` file, you'll find that there is a single call to an appifyr function - `appify`.

```
some_function <- function(a, b, c) {
  # Your R code here
  # ...
  # ...
  
  # Return plot!
}

appify(f = some_function, inps = list_of_inputs)
```

Currently appifyr only supports plot object as return value, but it supports very flexibel input definition - you can learn more in [this article](02-inputs.html).

The supports for rmarkdown to r-package conversion is experimental. There are some cases where it will not work, e.g. you can't read a file like you normally would nor can you access variables in the global environment. The function needs to be selfcontained.

For more reliable behavior you might want to write your function directly as R-package functions (`R/`) and save your data as `.Rda` files in the package's `data/` directory.

