on:
  push:
    branches:
      - main
      - master
      - dev

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown
          needs: website

      - name: Install package
        run: R CMD INSTALL .

      - name: Build site
        run: |
          pkgdown::build_site()
        shell: Rscript {0}
        
      - name: Create .nojekyll file
        run: touch docs/.nojekyll
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          branch: gh-pages
          clean: true
